name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Refresh pip cache
      run: |
        python -m pip cache purge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'numpy>=1.22,<1.24.3'
        pip install tensorflow==2.13.1
        pip install tf-agents==0.16.0
        pip install tensorflow-probability==0.24.0
        pip install keras>=2.13.0,<2.14
        pip install flake8
        pip install pytest

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        pytest
